services:
    postgres:
        image: postgres
        environment:
            POSTGRES_USER: user
            POSTGRES_PASSWORD: user
            POSTGRES_DB: user
        ports:
        - "5433:5432"
        
        