services:
    postgres:
        image: postgres
        environment:
            POSTGRES_USER: project
            POSTGRES_PASSWORD: project
            POSTGRES_DB: project
        ports:
        - "5434:5432"
        
        