/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ConfirmDeletePopup: typeof import('./components/confirmDeletePopup.vue')['default']
    CreateProjectPopup: typeof import('./components/createProjectPopup.vue')['default']
    ErrorPopup: typeof import('./components/ErrorPopup.vue')['default']
    HelloWorld: typeof import('./components/HelloWorld.vue')['default']
    LoadingScreen: typeof import('./components/LoadingScreen.vue')['default']
    LogoutPopup: typeof import('./components/LogoutPopup.vue')['default']
    Navbar: typeof import('./components/Navbar.vue')['default']
    ProjectCard: typeof import('./components/ProjectCard.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SettingsDropDown: typeof import('./components/SettingsDropDown.vue')['default']
    ToolsPopup: typeof import('./components/ToolsPopup.vue')['default']
  }
}
