/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<'/', '/', Record<never, never>, Record<never, never>>,
    '/ChooseRegister': RouteRecordInfo<'/ChooseRegister', '/ChooseRegister', Record<never, never>, Record<never, never>>,
    '/ChooseSubscription': RouteRecordInfo<'/ChooseSubscription', '/ChooseSubscription', Record<never, never>, Record<never, never>>,
    '/EditProfile': RouteRecordInfo<'/EditProfile', '/EditProfile', Record<never, never>, Record<never, never>>,
    '/Login': RouteRecordInfo<'/Login', '/Login', Record<never, never>, Record<never, never>>,
    '/Payment': RouteRecordInfo<'/Payment', '/Payment', Record<never, never>, Record<never, never>>,
    '/Perfil': RouteRecordInfo<'/Perfil', '/Perfil', Record<never, never>, Record<never, never>>,
    '/Project': RouteRecordInfo<'/Project', '/Project', Record<never, never>, Record<never, never>>,
    '/ProjectsList': RouteRecordInfo<'/ProjectsList', '/ProjectsList', Record<never, never>, Record<never, never>>,
    '/Register': RouteRecordInfo<'/Register', '/Register', Record<never, never>, Record<never, never>>,
    '/RegisterAnonymous': RouteRecordInfo<'/RegisterAnonymous', '/RegisterAnonymous', Record<never, never>, Record<never, never>>,
    '/Subscriptions': RouteRecordInfo<'/Subscriptions', '/Subscriptions', Record<never, never>, Record<never, never>>,
    '/ViewSubscriptions': RouteRecordInfo<'/ViewSubscriptions', '/ViewSubscriptions', Record<never, never>, Record<never, never>>,
  }
}
