# Use a specific Node.js LTS version for consistency and lightweight image
FROM node:18-bookworm-slim

# Set the working directory inside the container
WORKDIR /app

# Copy only necessary files for dependency installation
COPY package*.json tsconfig.json ./

# Install dependencies (production-only if needed)
RUN npm install

# Copy the rest of the application source code
COPY . .

# Set default environment variables
ENV PORT=${PORT} \
    NODE_ENV=development

# Expose the default internal port (2999), do not change
EXPOSE 2999
# Command to start the application
CMD ["npm", "run", "dev"] 