# using node lts bookworm slim, for lightweight, performance and compatibility 
FROM node:lts-bookworm-slim
# Setting working directory 
WORKDIR /app
# Copy package.json and package-lock.json to the working directory
COPY package*.json ./
COPY tsconfig.json ./
# Install dependencies
RUN npm install
# Copy src to the machine 
COPY src ./src
# Set default environment variables
ENV PORT=3000 \
    NODE_ENV=development\
    POSTGRES_USER=project\
    POSTGRES_PASS=project\
    POSTGRES_DB=project
# Expose the default internal port (3000), do not change
EXPOSE 3000
# Command to start the application
CMD ["npm", "run", "dev"] 