DROP SCHEMA bd_tp;

CREATE SCHEMA IF NOT EXISTS bd_tp;
USE bd_tp;


CREATE TABLE Curso (
	ID INT NOT NULL AUTO_INCREMENT,
	PRIMARY KEY (ID),
    NOME VARCHAR(45)
);

CREATE TABLE Turma(
	ID INT NOT NULL AUTO_INCREMENT,
    PRIMARY KEY (ID),
    N_ALUNOS INT NOT NULL,
    ID_CURSO INT,
    FOREIGN KEY (ID_CURSO) REFERENCES Curso(ID)
);

CREATE TABLE Disciplina (
	ID INT NOT NULL AUTO_INCREMENT,
    PRIMARY KEY (ID),
    NOME VARCHAR(45),
    MEDIA DECIMAL(20,2),
    ID_CURSO INT,
    FOREIGN KEY (ID_CURSO) REFERENCES Curso(ID)
);


CREATE TABLE Aula (
	ID INT NOT NULL AUTO_INCREMENT,
    PRIMARY KEY(ID),
    DATA_AULA DATE,
    DURACAO INT,
    ID_DISCIPLINA INT,
    FOREIGN KEY (ID_DISCIPLINA) REFERENCES Disciplina(ID)
);

CREATE TABLE Plataforma_de_Apoio (
	ID INT NOT NULL AUTO_INCREMENT,
	PRIMARY KEY (ID),
	NOME VARCHAR(45)
);

CREATE TABLE Recurso (
	ID INT NOT NULL AUTO_INCREMENT,
	PRIMARY KEY (ID),
    ANEXO VARCHAR(100),
    HORA_PUBLICACAO TIME,
    DESCRICAO VARCHAR(100),
    ID_PLATAFORMA_DE_APOIO INT,
    FOREIGN KEY (ID_PLATAFORMA_DE_APOIO) REFERENCES Plataforma_de_Apoio(ID)
);

CREATE TABLE EncarregadoEducacao (
	ID INT NOT NULL AUTO_INCREMENT,
	PRIMARY KEY (ID),
    NOME VARCHAR(45),
    PROFISSAO VARCHAR(45),
	GRAU_ESCOLARIDADE VARCHAR(45)
);

CREATE TABLE Aluno (
	NUMERO INT NOT NULL AUTO_INCREMENT,
	PRIMARY KEY (NUMERO),
    NOME VARCHAR(45),
    IDADE INT,
    SEXO VARCHAR(1),
    EMAIL VARCHAR(45),
    MEDIA DECIMAL(20,2),
    NUMERO_HORAS_ESTUDO_DIARIAS INT,
    ID_TURMA INT,
    FOREIGN KEY (ID_TURMA) REFERENCES Turma(ID),
    ID_EncarregadoEducacao INT,
    FOREIGN KEY (ID_EncarregadoEducacao) REFERENCES EncarregadoEducacao(ID)
);

CREATE TABLE Hobbie_Academico (
	ID INT NOT NULL AUTO_INCREMENT,
	PRIMARY KEY (ID),
    DESCRICAO VARCHAR(45),
    NUMERO_ALUNO INT,
    FOREIGN KEY (NUMERO_ALUNO) REFERENCES Aluno(NUMERO)
);


CREATE TABLE Professor (
	ID INT NOT NULL AUTO_INCREMENT,
	PRIMARY KEY (ID),
    NOME VARCHAR(45),
    EMAIL VARCHAR(45),
    ID_DISCIPLINA INT,
    FOREIGN KEY (ID_DISCIPLINA) REFERENCES Disciplina(ID)
);



CREATE TABLE Avaliacao (
	NUMERO INT NOT NULL AUTO_INCREMENT,
    PRIMARY KEY (NUMERO),
    DATA_AULA DATE,
    NOTA DECIMAL(4,2),
    ID_PROFESSOR INT,
    FOREIGN KEY (ID_PROFESSOR) REFERENCES Professor(ID),
    NUMERO_ALUNO INT,
    FOREIGN KEY (NUMERO_ALUNO) REFERENCES Aluno(NUMERO),
    ID_DISCIPLINA INT,
    FOREIGN KEY (ID_DISCIPLINA) REFERENCES DISCIPLINA(ID)
);

CREATE TABLE Acesso (
	ID_UTILIZADOR INT NOT NULL AUTO_INCREMENT,
    PRIMARY KEY (ID_UTILIZADOR),
    PASSE VARCHAR(45),
    ID_RECURSO INT,
    FOREIGN KEY (ID_RECURSO) REFERENCES Recurso(ID),
    ID_PROFESSOR INT,
    FOREIGN KEY (ID_PROFESSOR) REFERENCES Professor(ID),
    NUMERO_ALUNO INT,
    FOREIGN KEY (NUMERO_ALUNO) REFERENCES Aluno(NUMERO)
);

CREATE TABLE Estatistica (
    ID INT NOT NULL AUTO_INCREMENT,
    PRIMARY KEY (ID),
    ASSIDUIDADE VARCHAR(10),
    JUSTIFICACAO VARCHAR(10),
    PARTICIPACAO VARCHAR(10),
    NUMERO_ALUNO INT,
    FOREIGN KEY (NUMERO_ALUNO) REFERENCES Aluno(NUMERO)
);

CREATE TABLE Curso_has_Disciplina (
	ID_DISCIPLINA INT,
    FOREIGN KEY (ID_DISCIPLINA) REFERENCES Disciplina(ID),
    ID_CURSO INT,
    FOREIGN KEY (ID_CURSO) REFERENCES Curso(ID)
);

CREATE TABLE Turma_has_Professor(
	ID_TURMA INT,
    FOREIGN KEY (ID_TURMA) REFERENCES Turma(ID),
    ID_PROFESSOR INT,
    FOREIGN KEY (ID_PROFESSOR) REFERENCES Professor(ID)
);








    
	